apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sonarr-helm-chart-value-overrides
  namespace: media
data:
  values.yaml: |-
    replicaCount: 1

    image:
      repository: "linuxserver/sonarr" # Special image to use sonarr over a VPN
      tag: "latest"
      pullPolicy: IfNotPresent

    env:
      - name: VPN_ENABLED
        value: "no" # Enable sonarr over VPN
      - name: LAN_NETWORK
        value: "172.16.10.0/24"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: ClusterIP
      port: 80

    volumes:
      - name: "nfs-data-volume"
        persistentVolumeClaim:
          claimName: "nfs-data-volume"
      - name: tv-shows
        nfs:
          server: datum.securait.local
          path: /volume1/video/tv-shows

    volumeMounts:
      - name: "nfs-data-volume"
        mountPath: "/config"
        subPath: "config/sonarr"
      - name: "nfs-data-volume"
        mountPath: "/downloads"
        subPath: "downloads/sonarr"
      - name: "tv-shows"
        mountPath: "/tv"
