apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: radarr-helm-chart-value-overrides
  namespace: media
data:
  values.yaml: |-
    replicaCount: 1

    image:
      repository: "linuxserver/radarr" # Special image to use radarr over a VPN
      tag: "latest"
      pullPolicy: IfNotPresent

    env:
      - name: VPN_ENABLED
        value: "no" # Enable radarr over VPN
      - name: LAN_NETWORK
        value: "172.16.10.0/24"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: ClusterIP
      port: 80

    volumes:
      - name: "nfs-data-volume"
        persistentVolumeClaim:
          claimName: "nfs-data-volume"
      - name: movies
        nfs:
          server: datum.securait.local
          path: /volume1/video/movies

    volumeMounts:
      - name: "nfs-data-volume"
        mountPath: "/config"
        subPath: "config/radarr"
      - name: "nfs-data-volume"
        mountPath: "/downloads"
        subPath: "downloads/radarr"
      - name: "movies"
        mountPath: "/movies"
