---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "media"
  name: "radarr-ingress"
spec:
  rules:
  - host: "radarr.k3s.securait.local"
    http:
      paths:
        - backend:
            service:
              name: "radarr"
              port:
                number: 80
          path: "/"
          pathType: Prefix
  tls:
  - hosts:
    - radarr.k3s.securait.local

