apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: metallb-helm-chart-value-overrides
  namespace: metallb-system
data:
  values.yaml: |-
    # paste chart values.yaml (indented) here and alter as required>