apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jackett-helm-chart-value-overrides
  namespace: jackett
data:
  values.yaml: |-
    replicaCount: 1

    image:
      repository: "gjeanmart/jackettvpn" # Special image to use Jackett over a VPN
      tag: "latest"
      pullPolicy: IfNotPresent 

    env:
      - name: VPN_ENABLED
        value: "no" # Enable Jackett over VPN
      - name: LAN_NETWORK
        value: "172.16.10.0/24"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"

    service:
      type: ClusterIP
      port: 80

    volumes:
      - name: "nfs-data-volume"
        persistentVolumeClaim:
          claimName: "nfs-data-volume"

    volumeMounts:
      - name: "nfs-data-volume"
        mountPath: "/config"
        subPath: "config/jackett"
      - name: "nfs-data-volume"
        mountPath: "/downloads"
        subPath: "downloads/jackett"

