apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-k3s.securait.local
  namespace: kube-system
spec:
  secretName: wildcard-k3s.securait.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.k3s.securait.local"
